development: &DEFAULTS
  bucket: jamseshpro
  access_key_id: <%= ENV['AKIAJBKNN5KVMJ4CYDWA'] %>
  secret_access_key: <%= ENV['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'] %>

test:
  <<: *DEFAULTS
  bucket: myapp_test

production:
  <<: *DEFAULTS
  bucket: myapp